### ISSUE TITLE
Create MOM6 Pan-Antarctic Regional configuration

### ISSUE THREAD

**Issue by micaeljtoliveira** [COSIMA/mom6-panan#13]
- Progress tracked in  [mom6-panan](https://github.com/COSIMA/mom6-panan)

**Comment by navidcy** [comment]
I don't understand this issue says that the progress is tracked in the repo? And the the issue links to the repo itself.
It's a bit confusing. Seems like a resolved issue for me. Right?

**Comment by adele-morrison** [comment]
Hmm, yeah, no idea. I'll close it. We have a panan config now!
