### ISSUE TITLE
Runoff for 1/20°

### ISSUE THREAD

**Issue by adele157** [COSIMA/mom6-panan#18]
We need to fix the regridding / mask of the 1/20° runoff.

At our 20/1/23 meeting @angus-g volunteered to do this. However we need to wait until the [1/20° bathymetry](https://github.com/COSIMA/mom6-panan/issues/12) has been redone, so we have a final land/sea mask.

@angus-g also volunteered to share his script and write some documentation so that we can repeat this process for the 1/40° config. @angus-g to chat to @micaeljtoliveira about adding this script to domain-tools.

**Comment by adele157** [comment]
We also need the coupler mask. And to add this to domain-tools with documentation also.

**Comment by angus-g** [comment]
Generating the mask is now documented [in the wiki](https://github.com/COSIMA/mom6-panan/wiki/Preparing-inputs-for-a-new-configuration#generating-the-exchange-grid)

**Comment by adele157** [comment]
So fast!!
