### ISSUE TITLE
1/40° grids, bathymetry, runoff, masks etc

### ISSUE THREAD

**Issue by adele157** [COSIMA/mom6-panan#19]
Once we have streamlined the process from the 1/20°, repeat making grids, bathymetry, runoff, masks etc for the 1/40° config.

@aekiss and @adele157 volunteered for this (with @micaeljtoliveira's help hopefully!)

**Comment by angus-g** [comment]
The [regional scripts](https://github.com/COSIMA/mom6-regional-scripts) should be handy for this, plus Ashley's work to make this a [step-by-step notebook](https://github.com/COSIMA/mom6-regional-scripts/pull/5). Not quite the most elegant workflow, but hopefully it works as a starting point!

**Comment by adele157** [comment]
I think this is well under way with no more discussion needed. We have all the inputs we need for the 1/10th and 1/20th and 1/40th is nearly there.
