### ISSUE TITLE
Delete diagnostics folder?

### ISSUE THREAD

**Issue by AndyHoggANU** [COSIMA/mom6-panan#3]
@angus-g - I have updated the diagnostics we have from this repo and posted them here: https://github.com/COSIMA/mom6-panan-diagnostics

As discussed, it is probably best to keep diagnostics separate from the run branches that are derived from this repo.

I have copied and improved most of the scripts in the current directory, the exception being the script that @ashjbarnes where I have just copied part of the `fix_zcoord` function for plotting.

My suggestion is that we get rid of the diagnostics in this repo. Any objections?

**Comment by angus-g** [comment]
I agree. It's probably also worth nuking the `runs` branch that I pushed up here too? I think it's probably a good thing to do sooner rather than later so we don't let the run configuration and diagnostics any more intertwined.

**Comment by angus-g** [comment]
Closed by c1915e876891efe582f56761513da360bb595a73
