### ISSUE TITLE
Regridding the 1/20th Boundary forcing to 1/40th

### ISSUE THREAD

**Issue by willaguiar** [COSIMA/mom6-panan#33]
I am trying to regrid the panan 1/20th boundary forcing to the 1/40th grid, but xesmf keeps returning this error:

_can't currently regrid a grid that contains a DE of width less than 2_

Which seems to be caused by xesmf requiring Lon,Lat,z coordinates, while the boundary forcing has only Lon,Z, and Lat is a single value. (It seems like this is [a problem people found before](https://www.ncl.ucar.edu/Support/talk_archives/2012/2116.html))

Has anyone here found this problem before and have a way to fix it? Or perhaps another suggested method for interpolation. @angus-g @adele157 @fabiobdias @micaeljtoliveira

1/20th boundary forcing: /g/data/x77/ahg157/inputs/mom6/panan/forcing_obc_shifted.nc
Issue relative to:  https://github.com/COSIMA/mom6-panan/issues/29#issuecomment-1469051318

**Comment by angus-g** [comment]
You might be able to use xarray's interp (although it might not handle the periodic boundary properly). Otherwise, you could just do 50/50 linear interpolation between the existing points since it's a double-resolution grid.

**Comment by willaguiar** [comment]
Thanks. For the 50/50 interpolation, do we need it to be mass conserving?(Interpolating T,S,U,V).
