### ISSUE TITLE
Move/copy all inputs to ik11

### ISSUE THREAD

**Issue by micaeljtoliveira** [COSIMA/mom6-panan#37]
We should try to have all the inputs in a single location, so they are easy to find and update. This should be in `/g/data/ik11/inputs/`, just like for the other models/configuratons. Once in a while this directory is copied to tape, so we would also have a backup, which is always a good thing.

I've already created the following directories on ik11:
```
/g/data/ik11/inputs/mom6/panan/01deg
/g/data/ik11/inputs/mom6/panan/0025deg
/g/data/ik11/inputs/mom6/panan/005deg
```

Currently 0025deg is empty, but the other two have each a directory named after the date it was created. For the moment, as things are changing quite fast, we can keep updating and adding the files in the existing directories, but later on the idea would be to follow a similar naming and updating scheme as is used for ACCESS-OM2. For ACCESS-OM2, every time a file gets updated, a new directory is created, with links to the unmodified files from the previous directory and with the new files added, replacing the old ones. 

Next is a list of all the needed files. Let me know if I missed something. I'm also not sure about the `temp_salt_init_z_0025.nc`
 and `hycom1_*.nc` files. Which ones are needed for each configuration?

01deg - `/g/data/ik11/inputs/mom6/panan/01deg/20230404`:
- [x] atmos_mosaic_tile1Xland_mosaic_tile1.nc
- [x] atmos_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] diag_rho2.nc
- [x] forcing
  - [x] ~~eta_init.nc~~
  - [x] ~~eta_init_panan.nc~~
  - [x] forcing_obc.nc
  - [x] ~~forcing_obc_shifted.nc~~
  - [x] ~~ocean_daily.nc~~
  - [x] temp_salt_init_z.nc
- [x] grid_spec.nc
- [x] ~~hycom1_75_800m.nc~~
- [x] hycom1_panant.nc
- [x] land_mask.nc
- [x] land_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] masks
- [x] ocean_hgrid.nc
- [x] ocean_mask.nc
- [x] ocean_mosaic.nc
- [x] ocean_topog.nc
- [x] ~~sponges~~
  - [x] ~~idamp_1deg_10d_linear.nc~~
  - [x] ~~sponge_uvts.nc~~
- [x] RYF.runoff_all.1990_1991.panan01_cropped.nc
- [x] vcoord.nc

005deg - `/g/data/ik11/inputs/mom6/panan/005deg/20230404`:
- [x] atmos_mosaic_tile1Xland_mosaic_tile1.nc
- [x] atmos_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] diag_rho2.nc
- [x] forcing
  - [x] ~~eta_init.nc~~
  - [x] forcing_obc.nc
  - [x] ~~ocean_daily.nc~~
  - [x] temp_salt_init_z.nc
- [x] grid_spec.nc
- [x] land_mask.nc
- [x] land_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] masks
- [x] ocean_hgrid.nc
- [x] ocean_mask.nc
- [x] ocean_mosaic.nc
- [x] ocean_topog.nc
- [x] runoff.nc
- [x] vcoord.nc

0025deg - `/g/data/ik11/inputs/mom6/panan/0025deg/20230320`:
- [x] atmos_mosaic_tile1Xland_mosaic_tile1.nc
- [x] atmos_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] diag_rho2.nc
- [x] forcing
  - [x] ~~eta_init.nc~~
  - [x] forcing_obc.nc
  - [x] ~~ocean_daily.nc~~
  - [x] temp_salt_init_z.nc
- [x] grid_spec.nc
- [x] land_mask.nc
- [x] land_mosaic_tile1Xocean_mosaic_tile1.nc
- [x] masks
- [x] ocean_hgrid.nc
- [x] ocean_mask.nc
- [x] ocean_mosaic.nc
- [x] ocean_topog.nc
- [x] vcoord.nc
- [x] runoff.nc
- [x] sea_num.nc

**Comment by micaeljtoliveira** [comment]
It would also be good to know if some of the listed files are not needed anymore.

**Comment by micaeljtoliveira** [comment]
Similarly, we should store the scripts used to generate the topographies in a central location, but probably not ik11.

**Comment by aekiss** [comment]
Thanks @micaeljtoliveira - re. scripts, we normally keep the canonical versions on github, and note in the metadata of each file what commit was used to generate it.

**Comment by angus-g** [comment]
I don't think the sponges are needed any more, and I guess it would probably be good to clarify the forcing: we should only need a single boundary forcing file, a single initial condition, and possibly an initial eta? So:
- `eta_init.nc`
- `forcing_obc.nc`
- `temp_salt_init_z.nc`

**Comment by micaeljtoliveira** [comment]
@angus-g Thanks for the explanation. 

So the question now is what files should I keep for the 0.1deg configuration:

- `forcing/eta_init.nc` or `forcing/eta_init_panan.nc`?
- `forcing/forcing_obc.nc` or `forcing/forcing_obc_shifted.nc`?
- `temp_salt_init_z.nc` or `temp_salt_init_z_0025.nc`?

**Comment by micaeljtoliveira** [comment]
I think option 1 is best. To keep track of how files got there, you can for example add a README file. If some of the files required a more complex workflow (e.g., the topography and related files), we should probably follow @aekiss suggestion and put the the script that was used to generated them on github.

**Comment by micaeljtoliveira** [comment]
@willaguiar You should now have write permissions on `/g/data/ik11/inputs/mom6/panan`, so feel free to copy the missing files for the 1/40th configuration whenever you have the opportunity.

**Comment by willaguiar** [comment]
> @willaguiar You should now have write permissions on `/g/data/ik11/inputs/mom6/panan`, so feel free to copy the missing files for the 1/40th configuration whenever you have the opportunity.

Thanks! I have now copied the initial conditions, and runoff to the 0025 dir. The boundary forcing still has some problem to be fixed, so I will wait to have the final one before moving to the dir.

**Comment by schmidt-christina** [comment]
I've gathered most of the necessary files for the 0.05deg configuration in the directory: `/g/data/ik11/inputs/mom6/panan/005deg/20230404/`

But I am still testing and it's not running correctly yet. Will let you know when it works.

**Comment by schmidt-christina** [comment]
I have copied all files and the 1/20th model has been running for the first 3 days. 

I still have one problem:

The filename for the supergrid is hardcoded somewhere and I can't find where. It was named ocean_hgrid_0025.nc, but I now renamed it to ocean_hgrid.nc to be consistent across resolutions. I updated MOM_input and SIS_input.

I get the following error:

`Starting to initialize atmospheric model at 20230405 135938.546

FATAL from PE   536: fms_io_mod(dimesion_size): failed at inquiring size of dimesion nx from file INPUT/ocean_hgrid_0025.nc
`

Can someone point me to the file that gets called here? @angus-g @aekiss 

For now I am cheating and used `ln -s ocean_hgrid.nc ocean_hgrid_0025.nc` so that it is running

**Comment by angus-g** [comment]
It's defined in `ocean_mosaic.nc`, so you could either change the `gridfiles` variable in that, or just regenerate the mosaic.

**Comment by micaeljtoliveira** [comment]
@schmidt-christina The grid filename is hard-coded in `ocean_mosaic.nc`.

**Comment by willaguiar** [comment]
@micaeljtoliveira I am doing some tests runs in the new dir. But the model seem to be unable to read /g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/*. Could you open reading access to the files in this dir?

**Comment by micaeljtoliveira** [comment]
@willaguiar The files seem to be readable by everyone:

```
$ ls -al /g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks
total 76
drwxrwsr-x+ 2 mo1833 ik11  4096 Mar 30 20:56 .
drwxrwsr-x+ 7 mo1833 ik11  4096 Apr  6 12:09 ..
-rw-rw-r--+ 1 mo1833 ik11  6548 Mar 20 10:27 mask_table.1198.141x35
-rw-rw-r--+ 1 mo1833 ik11 14161 Mar 30 20:56 mask_table.2431.204x48
-rw-rw-r--+ 1 mo1833 ik11 14826 Mar 30 15:50 mask_table.2537.202x50
-rw-rw-r--+ 1 mo1833 ik11 18339 Mar 30 20:21 mask_table.3093.220x56
-rw-rw-r--+ 1 mo1833 ik11  2848 Mar 20 10:27 mask_table.580.100x25
-rw-rw-r--+ 1 mo1833 ik11  2946 Mar 20 10:27 mask_table.596.102x25
```
Same for ACL's, so I'm not sure what else I could do...

**Comment by angus-g** [comment]
Might be useful to see the actual error message too, @willaguiar?

**Comment by willaguiar** [comment]
Hi Micael!
When I ` ls  /g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks` I get that error back:
```
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.3093.220x56': Permission denied
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.2431.204x48': Permission denied
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.2537.202x50': Permission denied
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.1198.141x35': Permission denied
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.596.102x25': Permission denied
ls: cannot access '/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks/mask_table.580.100x25': Permission denied
mask_table.1198.141x35  mask_table.2431.204x48  mask_table.2537.202x50  mask_table.3093.220x56  mask_table.580.100x25  mask_table.596.102x25
```


When I run the model setting  `.../masks/mask_table.3093.220x56`as the dir for the masks I get the following error:
`FATAL from PE     0: MPP_DEFINE_DOMAINS(mpp_compute_extent): domain extents must be positive definite.`
But if set `../masks_open/ mask_table.3093.220x56`(I copied the masks I had on `/home/156/wf4500/mom6-panan/input_1_40th/masks2/ ` to `/g/data/ik11/inputs/mom6/panan/0025deg/20230320/masks_open/`) then no error occurs with the masks.

**Comment by micaeljtoliveira** [comment]
@willaguiar Could you try it now?

**Comment by willaguiar** [comment]
> @willaguiar Could you try it now?

`ls` now get the correct listing without the permission denied error now.  Waiting for the run to start to see if the error goes away

**Comment by micaeljtoliveira** [comment]
Okay, so the issue was the ACL's on the `masks` directory, not the files. You only had read and write permissions for the directory. I now added the execute permission.

**Comment by willaguiar** [comment]
Thanks! Model error `FATAL from PE 0: MPP_DEFINE_DOMAINS(mpp_compute_extent): domain extents must be positive definite. ` disappeared now with the new permission.

**Comment by willaguiar** [comment]
All files for panan0025 are now in `/g/data/ik11/inputs/mom6/panan/0025deg/20230320` with their respective names.  Panan0025 is running without any errors with these. There are two folders with the old forcing (OM2 year 156, not working) and old topography before the edits in the Ross Sea. I'll delete them later today if there are no objections.

**Comment by micaeljtoliveira** [comment]
@willaguiar Awesome! Thanks

I think we can now close this issue :)
