### ISSUE TITLE
How to initialize age tracer?

### ISSUE THREAD

**Issue by schmidt-christina** [COSIMA/mom6-panan#41]
The 1/20th run is in year 8 now and I want to switch on the age tracer. I now know what to include in MOM_input and diag_table, but get this error:

`FATAL from PE     1: MOM_restart: Unable to find mandatory variable age in restart files`

Can I just copy one of the files from the most recent restart, set everything to zero and name that file MOM.res_(n+1).nc with n being the number of restart files I have?

**Comment by angus-g** [comment]
I think something like that might work, yeah. I'm not sure how the restart file naming works, it might just read them sequentially. Worth a shot anyway, rather than having to reinitialise from scratch?

**Comment by PaulSpence** [comment]
I think the code allows for initial age in the middle of the run without restarts.

see var tracers_may_reinit in

https://github.com/mom-ocean/MOM6/blob/1e54bed6ac19799cf6cf2b34c20e914f730a3e3b/src/tracer/ideal_age_example.F90

call get_param(param_file, mdl, "TRACERS_MAY_REINIT", CS%tracers_may_reinit, &
                 "If true, tracers may go through the initialization code "//&
                 "if they are not found in the restart files.  Otherwise "//&
                 "it is a fatal error if the tracers are not found in the "//&
                 "restart files of a restarted run.", default=.false.)

logical :: tracers_may_reinit  !< If true, these tracers be set up via the initialization code if
                                 !! they are not found in the restart files.

**Comment by angus-g** [comment]
Even better! Nice find

**Comment by PaulSpence** [comment]
it was a pain in mom5 that I assumed the brilliance of GfDL would fix.

**Comment by schmidt-christina** [comment]
The way I described above also worked.
