### ISSUE TITLE
Error running panan-005 branch

### ISSUE THREAD

**Issue by adele-morrison** [COSIMA/mom6-panan#52]
I tried running the panan-005 branch, and it currently has this line in the config.yaml:
`run: /scratch/x77/ahg157/software/get_output.sh` but it failed because that file no longer exists. The output was left in the work/ directory and not collated.

@schmidt-christina, @angus-g: What does that file do? Should we put it somewhere more permanent than scratch if it's needed?

**Comment by schmidt-christina** [comment]
I had the same problem a while ago. @angus-g  then pointed me to this directory: `/g/data/x77/ahg157/software/get_output.sh` But now I can't check if it's still there as I am not a member of x77 anymore.

**Comment by adele-morrison** [comment]
Awesome, thanks @schmidt-christina. I'll move it to ik11 and update the repo.

(Feel free to join x77 again now if you like - panel meeting is over.)
